title: Accurate Hijri Calculator
description: This is the website of Accurate Hijri Calculator, a self-contained software for calculating Islamic Lunar Calendar.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
